const g = require('./general.js')

const aVeryBigSum = g.aVeryBigSum([1, 2, 3, 5555555])
console.log('aVeryBigSum', aVeryBigSum, aVeryBigSum === 5555561)
console.log('diagonalDifference', g.diagonalDifference([[1, 2, 15], [4, 5, 6], [7, 8, 9]]))
console.log('miniMaxSum', g.miniMaxSum([1, 2, 3, 4, 5]))
console.log('iceCreamParlor', g.iceCreamParlor(9, [1, 3, 4, 6, 7, 9]))

console.log(100)
console.log('2:', g.changeMoney(100)?.two, g.changeMoney(100)?.two === 0)
console.log('5:', g.changeMoney(100)?.five, g.changeMoney(100)?.five === 0)
console.log('10:', g.changeMoney(100)?.ten, g.changeMoney(100)?.ten === 10)
console.log(43)
console.log('2:', g.changeMoney(43)?.two, g.changeMoney(43)?.two === 4)
console.log('5:', g.changeMoney(43)?.five, g.changeMoney(43)?.five === 1)
console.log('10:', g.changeMoney(43)?.ten, g.changeMoney(43)?.ten === 3)
console.log(11)
console.log('2:', g.changeMoney(11)?.two, g.changeMoney(11)?.two === 3)
console.log('5:', g.changeMoney(11)?.five, g.changeMoney(11)?.five === 1)
console.log('10:', g.changeMoney(11)?.ten, g.changeMoney(11)?.ten === 0)
console.log(15)
console.log('2:', g.changeMoney(15)?.two, g.changeMoney(15)?.two === 0)
console.log('5:', g.changeMoney(15)?.five, g.changeMoney(15)?.five === 1)
console.log('10:', g.changeMoney(15)?.ten, g.changeMoney(15)?.ten === 1)
